name: CI - Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  Build:
    uses:   azure-prep/roboshop-github-actions/.github/workflows/ci-dev.yml@main
    with:
      appType: 'python'
      appName: 'payment'
    secrets:
      vault_token: ${{ secrets.TOKEN }}